language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2

before_script:
- composer self-update
- composer install --no-interaction
- mkdir -p build/logs

script:
- ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
- ./vendor/bin/phpcs

after_success:
- php vendor/bin/php-coveralls -v
